### ISSUE TITLE
Multi-threaded ranger screening

### ISSUE THREAD

**Issue by ck37** [saraemoore/SLWeightedScreen#1]
Hello,

Great stuff in here, I am finally giving this package a try. One small request: it would be helpful to pass-through the number of threads in screen.ranger to allow for multi-threaded screening. This can really speed up an algorithm when running sequential SuperLearner.

Thanks,
Chris

**Comment by saraemoore** [comment]
Thanks for giving it a try! And good idea. The pass-through is now implemented (as `numThreads` with default 1).

**Comment by ck37** [comment]
Awesome, thanks :)
